version: '2.2'
services:
  backend:
    build: ./backend
    ports:
      - "5005:5005"  # Assuming your backend runs on port 5005. Change as needed.
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5005
      - DRR_ASSET_PATH=./assets
    env_file:
      - .env
  frontend:
    build: 
      context: ./frontend/drr_frontend
      args:
        - REACT_APP_BACKEND_URL
    environment:
      - REACT_APP_BACKEND_URL
    ports:
      - "80:80"  # Your frontend will now be accessible on port 80

